"""create investigation model

Revision ID: 0a44cc4bf1e8
Revises: 533f7f52f34f
Create Date: 2026-07-31 19:21:29.453874

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0a44cc4bf1e8"
down_revision: str | Sequence[str] | None = "533f7f52f34f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "investigations",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "CREATED",
                "QUEUED",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                name="investigation_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum("LOW", "MEDIUM", "HIGH", "CRITICAL", name="investigation_priority"),
            nullable=False,
        ),
        sa.Column("owner_id", sa.String(length=36), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_investigation_created_at", "investigations", ["created_at"], unique=False
    )
    op.create_index(
        "ix_investigation_owner", "investigations", ["owner_id"], unique=False
    )
    op.create_index(
        "ix_investigation_priority", "investigations", ["priority"], unique=False
    )
    op.create_index(
        "ix_investigation_status", "investigations", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_investigation_status", table_name="investigations")
    op.drop_index("ix_investigation_priority", table_name="investigations")
    op.drop_index("ix_investigation_owner", table_name="investigations")
    op.drop_index("ix_investigation_created_at", table_name="investigations")
    op.drop_table("investigations")
    # ### end Alembic commands ###
